package model;
// Generated 27-Oct-2015 06:40:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="hair_uk"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String forenames;
     private String surnames;
     private String email;
     private String username;
     private String password;

    public User() {
    }

    public User(String forenames, String surnames, String email, String username, String password) {
       this.forenames = forenames;
       this.surnames = surnames;
       this.email = email;
       this.username = username;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="forenames", nullable=false, length=200)
    public String getForenames() {
        return this.forenames;
    }
    
    public void setForenames(String forenames) {
        this.forenames = forenames;
    }

    
    @Column(name="surnames", nullable=false, length=200)
    public String getSurnames() {
        return this.surnames;
    }
    
    public void setSurnames(String surnames) {
        this.surnames = surnames;
    }

    
    @Column(name="email", nullable=false, length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="username", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


